### ISSUE TITLE
Allow for full path for baseDir

### ISSUE THREAD

**Issue by mlarcher** [javoire/browserify-ng-html2js#13]
BaseDir option will only accept a partial path, that is supposed to begin after the process.cwd(). 
In some cases, it would be helpful to be able to pass an entire path to exclude, starting from the root directory, instead.

**Comment by javoire** [comment]
Ah! @shanestillwell, do you have an opinion on this since you created the `baseDir` feature? :)

**Comment by shanestillwell** [comment]
Should be doable since we assume the `baseDir` begins in the app root with our `process.cwd()`
https://github.com/javoire/browserify-ng-html2js/blob/2877ebb9d338980b1d20bece7eb6c30e197f4bd1/lib/index.js#L31

We'd just have to figure out if the path is absolute or relative and use `process.cwd()` if it's relative.

@mlarcher are you going to submit a pull request for this feature?

**Comment by mlarcher** [comment]
@shanestillwell, Are you sure there isn't something more generic to be found by matching the provided baseDir with a regex against the path ?
I don't intend to submit a PR for lack of time to dig the matter, just wanted to raise the issue.

**Comment by javoire** [comment]
So I think this one got fixed by #26
